//
//  Parameters.h
//  GAZREY.FRAME_1.0
//
//  Created by ZhuWeijie on 14-7-30.
//  Copyright (c) 2014年 zwj. All rights reserved.
//



#define USER_IS_VERTY @"USER_IS_VERTY"
#define USER_IS_BIND @"USER_IS_BIND"
#define TOUCH_PASS @"TOUCH_PASS"
#define USER_IS_LOGIN @"USER_IS_LOGIN"
#define USER_PASS @"USER_PASS"
#define USER_ACCOUNT @"USER_ACCOUNT"
#define USER_TEL @"USER_TEL"
#define INDEXCELL_TO_INVEST @"INDEXCELL_TO_INVEST"
#define SIGN_DAYS @"SIGN_DAYS"
#define USER_AVATAR @"USER_AVATAR"
#define USER_BANKACCOUNT @"USER_BANKACCOUNT"
#define USER_BANKANAME @"USER_BANKANAME"
#define USER_AUTH @"USER_AUTH"
#define USER_NAME @"USER_NAME"
#define OPEN_TOUCH_PASS @"OPEN_TOUCH_PASS"


#define LOGINURL @"LOGINURL"

#define USERISOPENAPP @"USERISOPENAPP"
