platform :ios, '7.0'
pod 'IQKeyboardManager', '~> 3.2.1.1'
pod 'MJRefresh', '~> 1.3.8'
pod 'EAIntroView', '~> 2.7.0'
pod 'JPushSDK', '~> 1.8.2'
pod 'SDWebImage', '~> 3.7.1'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'MJExtension'
pod 'FlatUIKit'
pod 'Masonry'
pod 'PNChart'
pod 'MMMaterialDesignSpinner'
pod 'SIAlertView', '~> 1.3'
pod 'ZBarSDK', '~> 1.3.1'
pod 'MBLocationManager'
pod 'FMDB', '~> 2.5'
pod 'YLProgressBar', '~> 3.5.2'
pod "FlickerNumber"
pod 'MZFormSheetController', '~> 3.0.3'
pod 'EAIntroView', '~> 2.7.0'